version: 2
updates:
    - package-ecosystem: maven
      directory: "/"
      schedule:
        interval: daily
        time: "04:00"
      open-pull-requests-limit: 10
      ignore:
         - dependency-name: org.apache.maven:*
           update-types:
             - major
         - dependency-name: org.eclipse.jgit:*
           update-types:
             - major
         - dependency-name: org.mockito:mockito-core
           update-types:
             - major
    - package-ecosystem: github-actions
      directory: "/.github"
      schedule:
         interval: weekly