sudo: false
dist: trusty
group: edge

matrix:
  include:
    - name: "Java 11"
      jdk: openjdk11
    - name: "Java 14"
      jdk: openjdk14

script:
  - mvn clean install -Pcoverage coveralls:report

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
