name: Build Smart Release Plugin

on:
  push:
  pull_request:
  schedule:
    - cron: '0 19 * * 6'

jobs:
  build:
    name: Maven Build JDK ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ '11', '17', '21' ]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
        cache: maven
    - name: Maven Build JDK ${{ matrix.java }}
      run: mvn -B package --file pom.xml -DskipTests
    - name: Maven Test JDK ${{ matrix.java }}
      run: mvn -B test --file pom.xml